#!/bin/sh
# key
if [ "$1" = "dogs" ]; then
KEY=spotify:track:1H5tvpoApNDxvxDexoaAUo
else
KEY=spotify:track:3odhGRfxHMVIwtNtc4BOZk
fi

# send request to dogvibes daemon
dbus-send --print-reply --system --dest=com.Dogvibes /com/dogvibes/amp/0 com.Dogvibes.Amp.Queue string:${KEY}
dbus-send --print-reply --system --dest=com.Dogvibes /com/dogvibes/amp/0 com.Dogvibes.Amp.Play
