#!/bin/bash

host=localhost:2000

function amp {
  curl http://$host/amp/0/$1
  echo
}

function dogvibes {
  curl http://$host/dogvibes/$1
  echo
}

dogvibes "search?query=oasis&callback=parseJSON"
dogvibes "search?query=oasis"

amp "queue?uri=spotify:track:3A3WCIkkm5MqGRnc4LT6fz"
amp "queue?uri=spotify:track:3ZlFUr0RBrUYYsmlcFvD0e"
amp "queue?uri=spotify:track:3q50J3nI1GOjDOwZDjt5Un"
amp "queue?uri=spotify:track:0S3gpZzlT9Hb7CCSV2owX7"
amp "queue?uri=spotify:track:69xL3vzKISEij96FrmWYNF"
amp "queue?uri=spotify:track:3Qvf812dY5JVlaZEbzI3nZ"
amp "queue?uri=spotify:track:7kXmJwrZGIhDaLT9sNo3ut"
amp "queue?uri=spotify:track:7rk75X26LwTEE8slwrqMjy"
amp "queue?uri=spotify:track:5WO8Vzz5hFWBGzJaNI5U5n"

amp "getAllTracksInQueue?callback=parseJSON"
#amp "removeFromQueue?nbr=0"
amp "getAllTracksInQueue"

amp "play"
sleep 2

amp "getStatus?callback=parseJSON"
amp "getStatus"

amp "connectSpeaker?nbr=0"
sleep 2

#amp "setVolume?level=3.0"
#sleep 2
#amp "setVolume?level=0.5"
#sleep 2
#amp "setVolume?level=1.0"
#sleep 2

amp "nextTrack"
amp "getQueuePosition"
sleep 2

amp "nextTrack"
amp "getQueuePosition"
sleep 2

amp "previousTrack"
amp "getQueuePosition"
sleep 2

# fixme: this one seems unstable...
#amp "playTrack?nbr=4"
#amp "getQueuePosition"
#sleep 2


amp "pause"
sleep 2

amp "play"

amp "getPlayedSeconds"
sleep 1
amp "getPlayedSeconds"
sleep 1
amp "getPlayedSeconds"
sleep 1

amp "disconnectSpeaker?nbr=0"
sleep 2

amp stop
sleep 2
